extract redirectUser method
benedmunds/CodeIgniter-Ion-Auth pull request #1228
Opened 2018-04-03 06:02 UTC by pabloleonalcaide

extract a 'redirectUser' method to avoid duplicated code

2018-04-03 12:57 UTC, benedmunds commented
Can you resolve the conflicts and resubmit (likely need to pull 3 in to your branch).

2018-04-05 10:55 UTC, pabloleonalcaide commented
Hi, I think that now there are no conflicts, sorry!

2018-04-05 13:05 UTC, benedmunds requested changes

2018-04-05 13:05 UTC, benedmunds commented on controllers/Auth.php
> +		if ($csrfkey && $csrfkey === $this->session->flashdata('csrfvalue')){
Move the curly brace to the next line to match other styling.

2018-04-06 13:14 UTC, benedmunds commented
Thanks! Looks good, merging.

2018-04-06 13:14 UTC, merged